### ISSUE TITLE
[Bug] UnicodeDecodeError on add-on start

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iagl#110]
I'm getting this UnicodeDecodeError on 2.1.2 on my laptop in Kodi 18.3... What's odd is I don't get the error on my Nvidia Shield 🤣

```
2019-08-09 11:26:05.066 T:2660  NOTICE: IAGL:  Lets Play!
2019-08-09 11:26:05.627 T:2660   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'utf8' codec can't decode byte 0xe2 in position 9999: unexpected end of data
                                            Traceback (most recent call last):
                                              File "C:\Users\David\Desktop\kodi\Leia 18.3\portable_data\addons\plugin.program.iagl\addon.py", line 1227, in <module>
                                                plugin.run(sys.argv)
                                              File "C:\Users\David\Desktop\kodi\Leia 18.3\portable_data\addons\script.module.routing\lib\routing.py", line 115, in run
                                                self._dispatch(path)
                                              File "C:\Users\David\Desktop\kodi\Leia 18.3\portable_data\addons\script.module.routing\lib\routing.py", line 126, in _dispatch
                                                view_func(**kwargs)
                                              File "C:\Users\David\Desktop\kodi\Leia 18.3\portable_data\addons\plugin.program.iagl\addon.py", line 42, in iagl_main
                                                IAGL.check_for_new_dat_files()
                                              File "C:\Users\David\Desktop\kodi\Leia 18.3\portable_data\addons\plugin.program.iagl\resources\lib\main.py", line 253, in check_for_new_dat_files
                                                header_string = byte_string.decode('utf-8')
                                              File "C:\Users\David\Desktop\kodi\Leia 18.3\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 9999: unexpected end of data
                                            -->End of Python script error report<--
2019-08-09 11:26:05.718 T:8332   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.iagl/
2019-08-09 11:26:05.735 T:8048   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.iagl/) failed
```

**Comment by zach-morris** [comment]
Try an uninstall and then re-install of the addon (if you had an old version installed) and remove the old userdata when you uninstall.  I thought I squashed this stupid bug for good.

**Comment by drinfernoo** [comment]
Hmm... it's working after doing that 🤣 Not sure what changed, because this was happening on a fresh install. Anyways, thanks!

**Comment by zach-morris** [comment]
It was a missing tag in the xml files that was the original issue:
```
<?xml version="1.0" encoding="UTF-8"?>
```
I've since added the tag to all the files, but if the files aren't updated then the bug remains.  Also annoying since python acts differently in this case depending on the OS (it's supposed to default to UTF-8 but doesn't for some reason in some cases).  Either way, I'll add some more bulletproofing to hopefully squash this once and for all.
