### ISSUE TITLE
Type error in downloadpath_resolved on LibreElec

### ISSUE THREAD

**Issue by drrak** [zach-morris/plugin.program.iagl#226]
```
2021-08-12 09:11:28.837 T:1111     INFO <general>: Enabled debug logging due to GUI setting. Level 2.
2021-08-12 09:11:28.838 T:1111    DEBUG <general>: ------ Window Init () ------
2021-08-12 09:11:29.054 T:1137    DEBUG <general>: PushCecKeypress - received key  b duration 226
2021-08-12 09:11:29.385 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 0
2021-08-12 09:11:29.417 T:1111    DEBUG <general>: HandleKey: 167 (0xa7, obc88) pressed, action is Down
2021-08-12 09:11:29.606 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 221
2021-08-12 09:11:29.829 T:1137    DEBUG <general>: PushCecKeypress - received key  b duration 0
2021-08-12 09:11:29.836 T:1111    DEBUG <general>: HandleKey: 11 (0x0b, obc244) pressed, action is Select
2021-08-12 09:11:30.053 T:1137    DEBUG <general>: PushCecKeypress - received key  b duration 224
2021-08-12 09:11:32.178 T:1137    DEBUG <general>: PushCecKeypress - received key c8 duration 0
2021-08-12 09:11:32.181 T:1111    DEBUG <general>: HandleKey: 200 (0xc8, obc55) pressed, action is activatewindow(home)
2021-08-12 09:11:32.181 T:1111    DEBUG <general>: Activating window ID: 10000
2021-08-12 09:11:32.403 T:1137    DEBUG <general>: PushCecKeypress - received key c8 duration 225
2021-08-12 09:11:32.487 T:1111    DEBUG <general>: ------ Window Deinit (SettingsCategory.xml) ------
2021-08-12 09:11:32.487 T:1111    DEBUG <general>: FreeVisualisation() done
2021-08-12 09:11:32.516 T:1111    DEBUG <general>: ------ Window Init (Home.xml) ------
2021-08-12 09:11:35.049 T:1137    DEBUG <general>: PushCecKeypress - received key c6 duration 0
2021-08-12 09:11:35.066 T:1111    DEBUG <general>: HandleKey: record (0xc6) pressed, action is activatewindow(favourites)
2021-08-12 09:11:35.066 T:1111    DEBUG <general>: Activating window ID: 10134
2021-08-12 09:11:35.066 T:1111    DEBUG <general>: ------ Window Init (DialogFavourites.xml) ------
2021-08-12 09:11:35.078 T:1577    DEBUG <general>: Thread JobWorker start, auto delete: true
2021-08-12 09:11:35.084 T:1574    DEBUG <general>: ffmpeg[0x3a60030X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2021-08-12 09:11:35.094 T:1577  WARNING <general>: CreateLoader - unsupported protocol(thumb) in thumb://None/
2021-08-12 09:11:35.094 T:1577    DEBUG <general>: GetImageHash - unable to stat url thumb://None/
2021-08-12 09:11:35.269 T:1137    DEBUG <general>: PushCecKeypress - received key c6 duration 220
2021-08-12 09:11:36.555 T:1137    DEBUG <general>: PushCecKeypress - received key a8 duration 0
2021-08-12 09:11:36.582 T:1111    DEBUG <general>: HandleKey: 168 (0xa8, obc87) pressed, action is Right
2021-08-12 09:11:36.774 T:1137    DEBUG <general>: PushCecKeypress - received key a8 duration 218
2021-08-12 09:11:37.125 T:1137    DEBUG <general>: PushCecKeypress - received key  b duration 0
2021-08-12 09:11:37.132 T:1111    DEBUG <general>: HandleKey: 11 (0x0b, obc244) pressed, action is Select
2021-08-12 09:11:37.133 T:1111    DEBUG <general>: Activating window ID: 10821
2021-08-12 09:11:37.349 T:1137    DEBUG <general>: PushCecKeypress - received key  b duration 224
2021-08-12 09:11:37.396 T:1111    DEBUG <general>: ------ Window Deinit (DialogFavourites.xml) ------
2021-08-12 09:11:37.472 T:1111    DEBUG <general>: ------ Window Deinit (Home.xml) ------
2021-08-12 09:11:37.472 T:1111    DEBUG <general>: FreeVisualisation() done
2021-08-12 09:11:37.501 T:1111    DEBUG <general>: CAddonDatabase: SELECT repo.id FROM repo .. took 0 ms
2021-08-12 09:11:37.524 T:1111    DEBUG <general>: CAddonDatabase: query  SELECT addons.*, repo.addonID AS repoID FROM addons JOIN addonlinkrepo ON addons.id=addonlinkrepo.idAddon JOIN repo ON repo.id=addonlinkrepo.idRepo WHERE addonlinkrepo.idRepo IN (4,40,283,284,328,340,353,354,355,356) ORDER BY repo.addonID, addons.addonID returned 1021 rows in 23 ms
2021-08-12 09:11:37.693 T:1111  WARNING <general>: Repository add-on repository.yt.testing_official uses plain HTTP for add-on downloads in path http://panicked.xyz/repository/youtube/python2/official_testing/zips - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2021-08-12 09:11:37.693 T:1111  WARNING <general>: Repository add-on repository.yt.testing_unofficial uses plain HTTP for add-on downloads in path http://panicked.xyz/repository/youtube/python2/unofficial_testing/zips - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2021-08-12 09:11:37.695 T:1111    DEBUG <general>: CAddonDatabase::GetAddons took 194 ms
2021-08-12 09:11:37.709 T:1111    DEBUG <general>: ADDONS: repo: repository.cdrepo - 14 addon(s) loaded
2021-08-12 09:11:37.709 T:1111    DEBUG <general>: ADDONS: repo: repository.exodusredux - 4 addon(s) loaded
2021-08-12 09:11:37.709 T:1111    DEBUG <general>: ADDONS: repo: repository.gamestarter - 1 addon(s) loaded
2021-08-12 09:11:37.709 T:1111    DEBUG <general>: ADDONS: repo: repository.kodi.game - 1 addon(s) loaded
2021-08-12 09:11:37.709 T:1111    DEBUG <general>: ADDONS: repo: repository.libreelec.tv - 207 addon(s) loaded
2021-08-12 09:11:37.709 T:1111    DEBUG <general>: ADDONS: repo: repository.thecrew - 27 addon(s) loaded
2021-08-12 09:11:37.709 T:1111    DEBUG <general>: ADDONS: repo: repository.xbmc.org - 659 addon(s) loaded
2021-08-12 09:11:37.709 T:1111    DEBUG <general>: ADDONS: repo: repository.yt.testing_official - 1 addon(s) loaded
2021-08-12 09:11:37.709 T:1111    DEBUG <general>: ADDONS: repo: repository.yt.testing_unofficial - 1 addon(s) loaded
2021-08-12 09:11:37.709 T:1111    DEBUG <general>: ADDONS: repo: repository.zachmorris - 4 addon(s) loaded
2021-08-12 09:11:37.717 T:1111  WARNING <general>: Repository add-on repository.yt.testing_official uses plain HTTP for add-on downloads in path http://panicked.xyz/repository/youtube/python2/official_testing/zips - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2021-08-12 09:11:37.717 T:1111  WARNING <general>: Repository add-on repository.yt.testing_unofficial uses plain HTTP for add-on downloads in path http://panicked.xyz/repository/youtube/python2/unofficial_testing/zips - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2021-08-12 09:11:37.754 T:1111    DEBUG <general>: ------ Window Init (MyGames.xml) ------
2021-08-12 09:11:37.757 T:1111    DEBUG <general>: CAddonDatabase: SELECT repo.id FROM repo .. took 0 ms
2021-08-12 09:11:37.772 T:1111    DEBUG <general>: CAddonDatabase: query  SELECT addons.*, repo.addonID AS repoID FROM addons JOIN addonlinkrepo ON addons.id=addonlinkrepo.idAddon JOIN repo ON repo.id=addonlinkrepo.idRepo WHERE addonlinkrepo.idRepo IN (4,40,283,284,328,340,353,354,355,356) ORDER BY repo.addonID, addons.addonID returned 1021 rows in 16 ms
2021-08-12 09:11:37.913 T:1111  WARNING <general>: Repository add-on repository.yt.testing_official uses plain HTTP for add-on downloads in path http://panicked.xyz/repository/youtube/python2/official_testing/zips - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2021-08-12 09:11:37.914 T:1111  WARNING <general>: Repository add-on repository.yt.testing_unofficial uses plain HTTP for add-on downloads in path http://panicked.xyz/repository/youtube/python2/unofficial_testing/zips - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2021-08-12 09:11:37.916 T:1111    DEBUG <general>: CAddonDatabase::GetAddons took 159 ms
2021-08-12 09:11:37.930 T:1111    DEBUG <general>: ADDONS: repo: repository.cdrepo - 14 addon(s) loaded
2021-08-12 09:11:37.930 T:1111    DEBUG <general>: ADDONS: repo: repository.exodusredux - 4 addon(s) loaded
2021-08-12 09:11:37.930 T:1111    DEBUG <general>: ADDONS: repo: repository.gamestarter - 1 addon(s) loaded
2021-08-12 09:11:37.930 T:1111    DEBUG <general>: ADDONS: repo: repository.kodi.game - 1 addon(s) loaded
2021-08-12 09:11:37.930 T:1111    DEBUG <general>: ADDONS: repo: repository.libreelec.tv - 207 addon(s) loaded
2021-08-12 09:11:37.930 T:1111    DEBUG <general>: ADDONS: repo: repository.thecrew - 27 addon(s) loaded
2021-08-12 09:11:37.930 T:1111    DEBUG <general>: ADDONS: repo: repository.xbmc.org - 659 addon(s) loaded
2021-08-12 09:11:37.930 T:1111    DEBUG <general>: ADDONS: repo: repository.yt.testing_official - 1 addon(s) loaded
2021-08-12 09:11:37.930 T:1111    DEBUG <general>: ADDONS: repo: repository.yt.testing_unofficial - 1 addon(s) loaded
2021-08-12 09:11:37.930 T:1111    DEBUG <general>: ADDONS: repo: repository.zachmorris - 4 addon(s) loaded
2021-08-12 09:11:37.938 T:1111  WARNING <general>: Repository add-on repository.yt.testing_official uses plain HTTP for add-on downloads in path http://panicked.xyz/repository/youtube/python2/official_testing/zips - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2021-08-12 09:11:37.938 T:1111  WARNING <general>: Repository add-on repository.yt.testing_unofficial uses plain HTTP for add-on downloads in path http://panicked.xyz/repository/youtube/python2/unofficial_testing/zips - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2021-08-12 09:11:37.976 T:1111    ERROR <general>: Control 55 in window 10821 has been asked to focus, but it can't
2021-08-12 09:11:38.032 T:1111    DEBUG <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.program.iagl/game_list/One Big List/Master_user_Favorites)
2021-08-12 09:11:38.032 T:1111    DEBUG <general>:   ParentPath = [plugin://plugin.program.iagl/game_list/One Big List/Master_user_Favorites]
2021-08-12 09:11:38.038 T:1111    DEBUG <general>: Loading items: 31, directory: plugin://plugin.program.iagl/game_list/One Big List/Master_user_Favorites sort method: 0, ascending: false
2021-08-12 09:11:38.067 T:1577    DEBUG <general>: CAddonDatabase::SetLastUsed[plugin.program.iagl] took 35 ms
2021-08-12 09:11:38.075 T:1577    DEBUG <general>: ffmpeg[0x985daa60X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2021-08-12 09:11:40.111 T:1137    DEBUG <general>: PushCecKeypress - received key  b duration 0
2021-08-12 09:11:40.133 T:1111    DEBUG <general>: HandleKey: 11 (0x0b, obc244) pressed, action is Select
2021-08-12 09:11:40.134 T:1111    DEBUG <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.program.iagl/game/MAME_ZachMorris/Track+%26+Field)
2021-08-12 09:11:40.134 T:1111    DEBUG <general>:   ParentPath = [plugin://plugin.program.iagl/game_list/One Big List/Master_user_Favorites]
2021-08-12 09:11:40.135 T:1578    DEBUG <general>: Thread waiting start, auto delete: false
2021-08-12 09:11:40.182 T:1574    DEBUG <general>: CAddonDatabase::SetLastUsed[plugin.program.iagl] took 48 ms
2021-08-12 09:11:40.182 T:1578    DEBUG <general>: StartScript - calling plugin Internet Archive Game Launcher('plugin://plugin.program.iagl/game/MAME_ZachMorris/Track+%26+Field','28','','resume:false')
2021-08-12 09:11:40.182 T:1579    DEBUG <general>: Thread LanguageInvoker start, auto delete: false
2021-08-12 09:11:40.183 T:1579     INFO <general>: initializing python engine.
2021-08-12 09:11:40.183 T:1579    DEBUG <general>: CPythonInvoker(32, /storage/.kodi/addons/plugin.program.iagl/addon.py): start processing
2021-08-12 09:11:40.229 T:1579    DEBUG <general>: -->Python Interpreter Initialized<--
2021-08-12 09:11:40.229 T:1579    DEBUG <general>: 
                                                   
2021-08-12 09:11:40.229 T:1579    DEBUG <general>: CPythonInvoker(32, /storage/.kodi/addons/plugin.program.iagl/addon.py): the source file to load is "/storage/.kodi/addons/plugin.program.iagl/addon.py"
2021-08-12 09:11:40.230 T:1579    DEBUG <general>: CPythonInvoker(32, /storage/.kodi/addons/plugin.program.iagl/addon.py): setting the Python path to /storage/.kodi/addons/plugin.program.iagl:/storage/.kodi/addons/plugin.video.youtube/resources/lib/:/storage/.kodi/addons/script.module.archive_tool/lib:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.dateutil/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.inputstreamhelper/lib:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.routing/lib:/storage/.kodi/addons/script.module.six/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/lib/python3.8/site-packages
2021-08-12 09:11:40.230 T:1579    DEBUG <general>: CPythonInvoker(32, /storage/.kodi/addons/plugin.program.iagl/addon.py): entering source directory /storage/.kodi/addons/plugin.program.iagl
2021-08-12 09:11:40.230 T:1579    DEBUG <general>: CPythonInvoker(32, /storage/.kodi/addons/plugin.program.iagl/addon.py): instantiating addon using automatically obtained id of "plugin.program.iagl" dependent on version 3.0.0 of the xbmc.python api
2021-08-12 09:11:40.235 T:1111    DEBUG <general>: ------ Window Init (DialogBusy.xml) ------
2021-08-12 09:11:40.325 T:1579     INFO <general>: IAGL:  Lets Play!
2021-08-12 09:11:40.325 T:1579    DEBUG <general>: IAGL:  Version 3.0.4
2021-08-12 09:11:40.333 T:1137    DEBUG <general>: PushCecKeypress - received key  b duration 222
2021-08-12 09:11:40.922 T:1579    DEBUG <general>: IAGL:  Cache Size set to - 1000000000.0 - 1GB
2021-08-12 09:11:40.996 T:1579    DEBUG <general>: [plugin.program.iagl][routing] Dispatching to 'get_game', args: {'game_list_id': 'MAME_ZachMorris', 'game_id': 'Track+%26+Field'}
2021-08-12 09:11:40.996 T:1579    DEBUG <general>: [plugin.program.iagl][routing] Dispatching to 'show_info_game', args: {'game_list_id': 'MAME_ZachMorris', 'game_id': 'Track+%26+Field'}
2021-08-12 09:11:40.997 T:1579    DEBUG <general>: IAGL:  Found game Track+%26+Field in list MAME_ZachMorris
2021-08-12 09:11:40.998 T:1579    DEBUG <general>: IAGL:  Info Page Initialized for game Track+%26+Field in list MAME_ZachMorris
2021-08-12 09:11:41.017 T:1111    DEBUG <general>: ------ Window Init (/storage/.kodi/addons/plugin.program.iagl/resources/skins/Default/1080i/IAGL-infodialog.xml) ------
2021-08-12 09:11:41.017 T:1111     INFO <general>: Loading skin file: /storage/.kodi/addons/plugin.program.iagl/resources/skins/Default/1080i/IAGL-infodialog.xml, load type: LOAD_ON_GUI_INIT
2021-08-12 09:11:41.081 T:1577    DEBUG <general>: ffmpeg[0x985daa60X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2021-08-12 09:11:41.270 T:1573     INFO <general>: Skipped 2 duplicate messages..
2021-08-12 09:11:41.270 T:1573    DEBUG <general>: ffmpeg[0x3ac9610X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2021-08-12 09:11:42.249 T:1137    DEBUG <general>: PushCecKeypress - received key a8 duration 0
2021-08-12 09:11:42.283 T:1111    DEBUG <general>: HandleKey: 168 (0xa8, obc87) pressed, action is Right
2021-08-12 09:11:42.469 T:1137    DEBUG <general>: PushCecKeypress - received key a8 duration 221
2021-08-12 09:11:42.639 T:1137    DEBUG <general>: PushCecKeypress - received key a8 duration 0
2021-08-12 09:11:42.683 T:1111    DEBUG <general>: HandleKey: 168 (0xa8, obc87) pressed, action is Right
2021-08-12 09:11:42.861 T:1137    DEBUG <general>: PushCecKeypress - received key a8 duration 222
2021-08-12 09:11:43.278 T:1137    DEBUG <general>: PushCecKeypress - received key  b duration 0
2021-08-12 09:11:43.283 T:1111    DEBUG <general>: HandleKey: 11 (0x0b, obc244) pressed, action is Select
2021-08-12 09:11:43.333 T:1111    DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
2021-08-12 09:11:43.384 T:1579    DEBUG <general>: [plugin.program.iagl][routing] Dispatching to 'download_and_launch_game', args: {'game_list_id': 'MAME_ZachMorris', 'game_id': 'Track+%26+Field'}
2021-08-12 09:11:43.387 T:1579    DEBUG <general>: IAGL:  Found game Track+%26+Field in list MAME_ZachMorris
2021-08-12 09:11:43.411 T:1579    DEBUG <general>: IAGL:  Downloader set to archive.org
2021-08-12 09:11:43.425 T:1579    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: expected str, bytes or os.PathLike object, not list
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.program.iagl/addon.py", line 899, in <module>
                                                       plugin.run(sys.argv)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.program.iagl/addon.py", line 406, in get_game
                                                       plugin.redirect('/game_info_page/'+game_list_id+'/'+game_id)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 133, in redirect
                                                       self._dispatch(path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.program.iagl/addon.py", line 424, in show_info_game
                                                       plugin.redirect('/game_launch/'+game_list_id+'/'+game_id)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 133, in redirect
                                                       self._dispatch(path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.program.iagl/addon.py", line 452, in download_and_launch_game
                                                       downloaded_files = iagl_download.download_game()
                                                     File "/storage/.kodi/addons/plugin.program.iagl/resources/lib/download.py", line 51, in download_game
                                                       current_dl = get_game_download_dict(emu_baseurl=self.game_list.get('emu_baseurl'),emu_downloadpath=self.game_list.get('emu_downloadpath_resolved'),emu_dl_source=self.game_list.get('download_source'),emu_post_processor=self.game_list.get('emu_postdlaction'),emu_launcher=self.game_list.get('emu_launcher'),emu_default_addon=self.game_list.get('emu_default_addon'),emu_ext_launch_cmd=self.game_list.get('emu_ext_launch_cmd'),game_url=cg.get('@name'),game_downloadpath=self.game.get('properties').get('emu_downloadpath'),game_post_processor=self.game.get('properties').get('emu_postdlaction'),game_launcher=self.game.get('properties').get('emu_launcher'),game_default_addon=self.game.get('properties').get('emu_default_addon'),game_ext_launch_cmd=self.game.get('properties').get('emu_ext_launch_cmd'),game_emu_command=self.game.get('properties').get('emu_command'),organize_default_dir=self.settings.get('download').get('organize_cache'),default_dir=self.directory.get('userdata').get('game_cache').get('path'),emu_name=self.game_list.get('emu_description'))
                                                     File "/storage/.kodi/addons/plugin.program.iagl/resources/lib/utils.py", line 1354, in get_game_download_dict
                                                       'downloadpath_resolved':Path(emu_downloadpath).joinpath(game_filename).expanduser(),
                                                     File "/usr/lib/python3.8/pathlib.py", line 1041, in __new__
                                                     File "/usr/lib/python3.8/pathlib.py", line 682, in _from_parts
                                                     File "/usr/lib/python3.8/pathlib.py", line 666, in _parse_args
                                                   TypeError: expected str, bytes or os.PathLike object, not list
                                                   -->End of Python script error report<--
                                                   
2021-08-12 09:11:43.425 T:1579    DEBUG <general>: onExecutionDone(32, /storage/.kodi/addons/plugin.program.iagl/addon.py)
2021-08-12 09:11:43.434 T:1111    DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-08-12 09:11:43.502 T:1137    DEBUG <general>: PushCecKeypress - received key  b duration 224
2021-08-12 09:11:43.540 T:1579    DEBUG <general>: .
2021-08-12 09:11:43.542 T:1111    DEBUG <general>: ------ Window Deinit (/storage/.kodi/addons/plugin.program.iagl/resources/skins/Default/1080i/IAGL-infodialog.xml) ------
2021-08-12 09:11:43.731 T:1579     INFO <general>: Python interpreter stopped
2021-08-12 09:11:43.732 T:1579    DEBUG <general>: Thread LanguageInvoker 2393895552 terminating
2021-08-12 09:11:43.737 T:1578    ERROR <general>: GetDirectory - Error getting plugin://plugin.program.iagl/game/MAME_ZachMorris/Track+%26+Field
2021-08-12 09:11:43.737 T:1578    DEBUG <general>: Thread waiting 2323640960 terminating
2021-08-12 09:11:43.750 T:1111    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.iagl/game/MAME_ZachMorris/Track+%26+Field) failed
2021-08-12 09:11:43.750 T:1111    DEBUG <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.program.iagl/game_list/One Big List/Master_user_Favorites)
2021-08-12 09:11:43.750 T:1111    DEBUG <general>:   ParentPath = [plugin://plugin.program.iagl/]
2021-08-12 09:11:43.756 T:1111    DEBUG <general>: Loading items: 31, directory: plugin://plugin.program.iagl/game_list/One Big List/Master_user_Favorites sort method: 0, ascending: false
2021-08-12 09:11:43.791 T:1574    DEBUG <general>: CAddonDatabase::SetLastUsed[plugin.program.iagl] took 41 ms
2021-08-12 09:11:50.238 T:1137    DEBUG <general>: PushCecKeypress - received key fe duration 0
2021-08-12 09:11:50.265 T:1111    DEBUG <general>: HandleKey: 254 (0xfe, obc1) pressed, action is activatewindow(systemsettings)
2021-08-12 09:11:50.266 T:1111    DEBUG <general>: Activating window ID: 10016
2021-08-12 09:11:50.460 T:1137    DEBUG <general>: PushCecKeypress - received key fe duration 222
2021-08-12 09:11:50.571 T:1111    DEBUG <general>: ------ Window Deinit (MyGames.xml) ------
2021-08-12 09:11:50.571 T:1111    DEBUG <general>: FreeVisualisation() done
2021-08-12 09:11:50.599 T:1111    DEBUG <general>: ------ Window Init (SettingsCategory.xml) ------
2021-08-12 09:11:52.130 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 0
2021-08-12 09:11:52.149 T:1111    DEBUG <general>: HandleKey: 167 (0xa7, obc88) pressed, action is Down
2021-08-12 09:11:52.354 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 225
2021-08-12 09:11:52.509 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 0
2021-08-12 09:11:52.515 T:1111    DEBUG <general>: HandleKey: 167 (0xa7, obc88) pressed, action is Down
2021-08-12 09:11:52.731 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 222
2021-08-12 09:11:52.861 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 0
2021-08-12 09:11:52.882 T:1111    DEBUG <general>: HandleKey: 167 (0xa7, obc88) pressed, action is Down
2021-08-12 09:11:53.084 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 224
2021-08-12 09:11:53.193 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 0
2021-08-12 09:11:53.215 T:1111    DEBUG <general>: HandleKey: 167 (0xa7, obc88) pressed, action is Down
2021-08-12 09:11:53.420 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 227
2021-08-12 09:11:53.612 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 0
2021-08-12 09:11:53.615 T:1111    DEBUG <general>: HandleKey: 167 (0xa7, obc88) pressed, action is Down
2021-08-12 09:11:53.834 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 222
2021-08-12 09:11:53.997 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 0
2021-08-12 09:11:54.015 T:1111    DEBUG <general>: HandleKey: 167 (0xa7, obc88) pressed, action is Down
2021-08-12 09:11:54.218 T:1137    DEBUG <general>: PushCecKeypress - received key a7 duration 221
2021-08-12 09:11:54.387 T:1111    DEBUG <general>: ------ Window Deinit (DialogNotification.xml) ------
2021-08-12 09:11:54.690 T:1137    DEBUG <general>: PushCecKeypress - received key a8 duration 0
2021-08-12 09:11:54.697 T:1111    DEBUG <general>: HandleKey: 168 (0xa8, obc87) pressed, action is Right
2021-08-12 09:11:54.910 T:1137    DEBUG <general>: PushCecKeypress - received key a8 duration 220
2021-08-12 09:11:55.319 T:1137    DEBUG <general>: PushCecKeypress - received key  b duration 0
2021-08-12 09:11:55.349 T:1111    DEBUG <general>: HandleKey: 11 (0x0b, obc244) pressed, action is Select
2021-08-12 09:11:55.349 T:1111     INFO <general>: Disabled debug logging due to GUI setting. Level 0.
```

_RPi4, LibreELEC 9.97.1, Kodi 19.1, IAGL 3.0.4_

**Comment by drrak** [comment]
Great, now even the earlier version doesn't work 😡

**Comment by zach-morris** [comment]
You're going to have to be more descriptive than 'nothing works'.

What is your download path set to?

**Comment by drrak** [comment]
More descriptive? Kodi.log is not descriptive enough?

Everything is at default settings. I haven't changed anything in version 3.0.3.

**Comment by zach-morris** [comment]
I don't think so.  Can you still recreate this issue?  One other user did a long time ago, but it seems like an error that occurs once and it's gone.

Also, you're saying that there was an error when it asked you to update game lists.  Can you recreate that issue?

**Comment by drrak** [comment]
Not anymore because even after uninstalling and reinstalling, I no longer have questions about NES and PSP. I chose "no, never" as I wrote before. But you should see this error in kodi.log.

**Comment by zach-morris** [comment]
Yes, thanks for the tips on how to troubleshoot.  I see the error, but it doesn't specifically point to the cause, so i need to (try to) recreate the problem.  Without steps to follow, I can't recreate the problem.

**Comment by zach-morris** [comment]
I believe i found the typo causing this issue, which is caused only if you're using multiple profiles in Kodi.  Should be fixed in the latest on github and available in the next release
