### ISSUE TITLE
Kodi Matrix v19.3 IAGL crash while run DOS game

### ISSUE THREAD

**Issue by expertup** [zach-morris/plugin.program.iagl#237]
When I try launch any DOS game, Kodi report bug

Form IAGL menu I select:
- "Search"
- "Enter title"
- Write "Secret agent"
- "Execute search"
- From result I select "MSDOS - Secret agent"
- "Launch"
- Is "Downloadeing - Secret agent (1992).zip"
- 
After moment is notification "Error The Internet Archive Game - check log file".

I found in internet, that domain `the-eye.eu` is closed. But why DOS games are listed on search result?

Logs:
```
24:12.159 T:12672    INFO <general>: IAGL:  Lets Play!
2022-01-03 11:24:16.491 T:12672    INFO <general>: CPythonInvoker(6, C:\Users\Dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\addon.py): script successfully run
2022-01-03 11:24:16.625 T:12672    INFO <general>: Python interpreter stopped
2022-01-03 11:26:07.812 T:232      INFO <general>: initializing python engine.
2022-01-03 11:26:07.913 T:232      INFO <general>: IAGL:  Lets Play!
2022-01-03 11:26:09.148 T:232      INFO <general>: CPythonInvoker(7, C:\Users\Dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\addon.py): script successfully run
2022-01-03 11:26:09.312 T:232      INFO <general>: Python interpreter stopped
2022-01-03 11:26:13.487 T:6260     INFO <general>: initializing python engine.
2022-01-03 11:26:13.586 T:6260     INFO <general>: IAGL:  Lets Play!
2022-01-03 11:26:14.721 T:11480    INFO <general>: Loading skin file: DialogKeyboard.xml, load type: KEEP_IN_MEMORY
2022-01-03 11:26:21.006 T:6260     INFO <general>: CPythonInvoker(8, C:\Users\Dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\addon.py): script successfully run
2022-01-03 11:26:21.007 T:11480 WARNING <general>: CGUIMediaWindow::OnMessage - updating in progress
2022-01-03 11:26:21.130 T:6260     INFO <general>: Python interpreter stopped
2022-01-03 11:26:21.135 T:9780    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.iagl/archives/Search/title
2022-01-03 11:26:21.139 T:11480   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.iagl/archives/Search/title) failed
2022-01-03 11:26:21.149 T:3496     INFO <general>: initializing python engine.
2022-01-03 11:26:21.255 T:3496     INFO <general>: IAGL:  Lets Play!
2022-01-03 11:26:22.390 T:3496     INFO <general>: CPythonInvoker(9, C:\Users\Dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\addon.py): script successfully run
2022-01-03 11:26:22.522 T:3496     INFO <general>: Python interpreter stopped
2022-01-03 11:26:23.806 T:13164    INFO <general>: initializing python engine.
2022-01-03 11:26:23.905 T:13164    INFO <general>: IAGL:  Lets Play!
2022-01-03 11:26:37.710 T:13164    INFO <general>: CPythonInvoker(10, C:\Users\Dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\addon.py): script successfully run
2022-01-03 11:26:37.853 T:13164    INFO <general>: Python interpreter stopped
2022-01-03 11:28:04.118 T:1172     INFO <general>: initializing python engine.
2022-01-03 11:28:04.221 T:1172     INFO <general>: IAGL:  Lets Play!
2022-01-03 11:28:06.028 T:11480    INFO <general>: Loading skin file: C:\Users\Dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\resources\skins\Default\1080i\IAGL-infodialog.xml, load type: LOAD_ON_GUI_INIT
2022-01-03 11:32:40.248 T:11480    INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2022-01-03 11:32:52.397 T:1172    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'generic_downloader' object has no attribute 'r'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connection.py", line 169, in _new_conn
                                                       conn = connection.create_connection(
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\util\connection.py", line 96, in create_connection
                                                       raise err
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\util\connection.py", line 86, in create_connection
                                                       sock.connect(sa)
                                                   socket.timeout: timed out
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 699, in urlopen
                                                       httplib_response = self._make_request(
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 382, in _make_request
                                                       self._validate_conn(conn)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 1010, in _validate_conn
                                                       conn.connect()
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connection.py", line 353, in connect
                                                       conn = self._new_conn()
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connection.py", line 174, in _new_conn
                                                       raise ConnectTimeoutError(
                                                   urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000002221C3D35E0>, 'Connection to the-eye.eu timed out. (connect timeout=12.1)')
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 439, in send
                                                       resp = conn.urlopen(
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 755, in urlopen
                                                       retries = retries.increment(
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\util\retry.py", line 574, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='the-eye.eu', port=443): Max retries exceeded with url: /public/Games/eXo/eXoDOS_v5/eXo/eXoDOS/Secret%20Agent%20%281992%29.zip (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002221C3D35E0>, 'Connection to the-eye.eu timed out. (connect timeout=12.1)'))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\resources\lib\download.py", line 599, in download
                                                       with self.session.get(url,verify=False,stream=True,timeout=self.timeout,headers=self.header) as self.r:
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 555, in get
                                                       return self.request('GET', url, **kwargs)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 504, in send
                                                       raise ConnectTimeout(e, request=request)
                                                   requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='the-eye.eu', port=443): Max retries exceeded with url: /public/Games/eXo/eXoDOS_v5/eXo/eXoDOS/Secret%20Agent%20%281992%29.zip (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002221C3D35E0>, 'Connection to the-eye.eu timed out. (connect timeout=12.1)'))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\addon.py", line 899, in <module>
                                                       plugin.run(sys.argv)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\addon.py", line 406, in get_game
                                                       plugin.redirect('/game_info_page/'+game_list_id+'/'+game_id)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 133, in redirect
                                                       self._dispatch(path)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\addon.py", line 424, in show_info_game
                                                       plugin.redirect('/game_launch/'+game_list_id+'/'+game_id)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 133, in redirect
                                                       self._dispatch(path)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\addon.py", line 452, in download_and_launch_game
                                                       downloaded_files = iagl_download.download_game()
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\resources\lib\download.py", line 76, in download_game
                                                       download_status = self.downloader.download(url=current_dl.get('url_resolved'),dest=current_dl.get('downloadpath_resolved'),est_size=cg.get('@size'),show_progress=show_progress)
                                                     File "C:\Users\Dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\resources\lib\download.py", line 624, in download
                                                       if self.r.status_code == 403:
                                                   AttributeError: 'generic_downloader' object has no attribute 'r'
                                                   -->End of Python script error report<--
                                                   
2022-01-03 11:32:52.413 T:14656    INFO <general>: CActiveAESink::OpenSink - initialize sink
2022-01-03 11:32:52.578 T:1172     INFO <general>: Python interpreter stopped
2022-01-03 11:32:52.588 T:14196   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.iagl/game/eXoDOS_ZachMorris/Secret+Agent
2022-01-03 11:32:52.658 T:11480   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.iagl/game/eXoDOS_ZachMorris/Secret+Agent) failed
2022-01-03 11:36:21.176 T:11480    INFO <general>: Loading skin file: DialogButtonMenu.xml, load type: KEEP_IN_MEMORY
```

**Comment by zach-morris** [comment]
Same issue I gather as #230.  Should be fixed in the next release.
