### ISSUE TITLE
Wizard is not starting on fresh install

### ISSUE THREAD

**Issue by sprnza** [zach-morris/plugin.program.iagl#240]
Hi there!
Thanks for the project!
I try to install it on RPI2 + Archlinuxarm. When I try to launch the addon and then select "Run wizard" I get this error:
```
2022-01-19 09:43:14.434 T:25510   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'ADDON_SPECIAL_PATH' is not defined
                                                   Traceback (most recent call last):
                                                     File "/home/alarm/.kodi/addons/plugin.program.iagl/addon.py", line 899, in <module>
                                                       plugin.run(sys.argv)
                                                     File "/home/alarm/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/home/alarm/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/home/alarm/.kodi/addons/plugin.program.iagl/addon.py", line 31, in index_route
                                                       xbmc.executebuiltin('RunScript(%(ADDON_SPECIAL_PATH)srun_IAGL_wizard.py)'%{'ADDON_SPECIAL_PATH':ADDON_SPECIAL_PATH})
                                                   NameError: name 'ADDON_SPECIAL_PATH' is not defined
                                                   -->End of Python script error report<--
```
what could be wrong?

**Comment by zach-morris** [comment]
Dumb error on my part, i'll push a fix shortly
