### ISSUE TITLE
Cannot change launcher for GBA AND DS

### ISSUE THREAD

**Issue by IAmAGitHubb** [zach-morris/plugin.program.iagl#277]
I can't change the launcher path on Kodi 20.1 when using IAGL.

It gives me an error every time, and I don't know manual launchers yet. In fact, that might not work...

Help?

**Comment by zach-morris** [comment]
I'd need more info, and maybe some steps to duplicate. You got a debug log?

**Comment by IAmAGitHubb** [comment]
How do you get a debug log?

**Comment by IAmAGitHubb** [comment]
For info. My device is android. Retro arch config in Retroarch/config/adyadyada. I select Gba/DS and select My boy for gba, or Drastic for ds. And it gives me an error.

**Comment by zach-morris** [comment]
Debug log instructions [here](https://kodi.wiki/view/Log_file/Easy#:~:text=Enable%20the%20setting%20Enable%20debug,Shift%20%2B%20d%20on%20a%20keyboard).  You can then upload the log with [the logfile uploader ](https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader) addon.

**Comment by djay** [comment]
@zach-morris I'm getting the same problem. Here is the exception I get
```
2023-03-24 21:12:30.622 T:32089   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'self' is not defined
                                                   Traceback (most recent call last):
                                                     File "/storage/2251-1EE7/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iagl/addon.py", line 902, in <module>
                                                       plugin.run(sys.argv)
                                                     File "/storage/2251-1EE7/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/2251-1EE7/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/2251-1EE7/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iagl/addon.py", line 675, in context_menu_select
                                                       if iagl_addon.settings.get('ext_launchers').get('environment') in ['android','android_ra32','android_aarch64'] and self.settings.get('ext_launchers').get('use_startactivity') and isinstance(current_choices[new_value].get('activity'),str):
                                                                                                                                                                          ^^^^
                                                   NameError: name 'self' is not defined
                                                   -->End of Python script error report<--
```

**Comment by zach-morris** [comment]
Thank you for the log.  Dumb mistake on my part. I think i fixed it and will update the addon shortly.

**Comment by zach-morris** [comment]
3.0.9 is uploaded, should be fixed now.  Let me know if you run into other issues.
