### ISSUE TITLE
[Bug] Error on opening lists

### ISSUE THREAD

**Issue by finkleandeinhorn** [zach-morris/plugin.program.iagl#88]
I'm getting this error on my Nvidia Shield, running Kodi 18.1, and the latest IAGL on the repo. Neither "Browse All Lists" nor "Browse by Category" work for me, and throw the following errors:

```
2019-05-09 16:45:29.571 T:7115  NOTICE: IAGL:  Lets Play!
2019-05-09 16:45:33.469 T:7115   ERROR: GetDirectory - Error getting /storage/F8F29C3CF29BFCD6/Android/data/org.xbmc.kodi/files//.kodi/addons/plugin.program.iagl/resources/data/dat_files
2019-05-09 16:45:40.815 T:7126  NOTICE: IAGL:  Lets Play!
2019-05-09 16:45:53.743 T:7126   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'utf8' codec can't decode byte 0xe2 in position 9999: unexpected end of data
                                            Traceback (most recent call last):
                                              File "/storage/F8F29C3CF29BFCD6/Android/data/org.xbmc.kodi/files//.kodi/addons/plugin.program.iagl/addon.py", line 1227, in <module>
                                                plugin.run(sys.argv)
                                              File "/storage/F8F29C3CF29BFCD6/Android/data/org.xbmc.kodi/files//.kodi/addons/script.module.routing/lib/routing.py", line 115, in run
                                                self._dispatch(path)
                                              File "/storage/F8F29C3CF29BFCD6/Android/data/org.xbmc.kodi/files//.kodi/addons/script.module.routing/lib/routing.py", line 126, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/F8F29C3CF29BFCD6/Android/data/org.xbmc.kodi/files//.kodi/addons/plugin.program.iagl/addon.py", line 94, in list_archives_by_category
                                                for list_item in IAGL.get_game_list_categories_as_listitems():
                                              File "/storage/F8F29C3CF29BFCD6/Android/data/org.xbmc.kodi/files//.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 874, in get_game_list_categories_as_listitems
                                                game_lists_dict = self.get_game_lists()
                                              File "/storage/F8F29C3CF29BFCD6/Android/data/org.xbmc.kodi/files//.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 695, in get_game_lists
                                                header_string = byte_string.decode('utf-8')
                                              File "/home/jenkins/workspace/Android-ARM64/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/encodings/utf_8.py", line 16, in decode
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 9999: unexpected end of data
                                            -->End of Python script error report<--
2019-05-09 16:45:53.971 T:7125   ERROR: GetDirectory - Error getting plugin://plugin.program.iagl/archives/categorized
2019-05-09 16:45:53.983 T:13006   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.iagl/archives/categorized) failed
2019-05-09 16:46:00.536 T:7198  NOTICE: IAGL:  Lets Play!
2019-05-09 16:46:07.331 T:7198   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'utf8' codec can't decode byte 0xe2 in position 9999: unexpected end of data
                                            Traceback (most recent call last):
                                              File "/storage/F8F29C3CF29BFCD6/Android/data/org.xbmc.kodi/files//.kodi/addons/plugin.program.iagl/addon.py", line 1227, in <module>
                                                plugin.run(sys.argv)
                                              File "/storage/F8F29C3CF29BFCD6/Android/data/org.xbmc.kodi/files//.kodi/addons/script.module.routing/lib/routing.py", line 115, in run
                                                self._dispatch(path)
                                              File "/storage/F8F29C3CF29BFCD6/Android/data/org.xbmc.kodi/files//.kodi/addons/script.module.routing/lib/routing.py", line 126, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/F8F29C3CF29BFCD6/Android/data/org.xbmc.kodi/files//.kodi/addons/plugin.program.iagl/addon.py", line 67, in list_archives_all
                                                for list_item in IAGL.get_game_lists_as_listitems():
                                              File "/storage/F8F29C3CF29BFCD6/Android/data/org.xbmc.kodi/files//.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 727, in get_game_lists_as_listitems
                                                game_lists_dict = self.get_game_lists()
                                              File "/storage/F8F29C3CF29BFCD6/Android/data/org.xbmc.kodi/files//.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 695, in get_game_lists
                                                header_string = byte_string.decode('utf-8')
                                              File "/home/jenkins/workspace/Android-ARM64/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/encodings/utf_8.py", line 16, in decode
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 9999: unexpected end of data
                                            -->End of Python script error report<--
2019-05-09 16:46:07.569 T:7197   ERROR: GetDirectory - Error getting plugin://plugin.program.iagl/archives/all
2019-05-09 16:46:07.575 T:13006   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.iagl/archives/all) failed
```

**Comment by zach-morris** [comment]
I think this is the same as this issue (which of course is some weird android only issue):
https://github.com/zach-morris/plugin.program.iagl/issues/51

It was fixed a while ago, but perhaps you have some old dat files in your setup?  Can you uninstall the addon, then re-install?

**Comment by zach-morris** [comment]
I pushed a change to the addon that will hopefully just squash this issue all together.  I can't recreate the problem though, can you update your addon from the latest git and retest?

**Comment by drinfernoo** [comment]
I was having a similar error, and reinstalling the add-on helped 👌

**Comment by zach-morris** [comment]
OK, I'm guessing its because some dat files did not get overwritten/updated when the fix was applied.  Long story short:  Android picks a default file encoding based on ??? (phase of the moon?  Roll of the dice?  I have no idea).

I added the header ```<?xml version="1.0" encoding="UTF-8"?>``` to all dat files which seems to force android to pick utf-8.  If you uninstall and re-install then all the dat files should have this in the header.

**Comment by finkleandeinhorn** [comment]
Yep, reinstalling worked for me too. Thanks for the help guys!
